# Generated by Django 2.0.7 on 2019-06-01 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190601_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='users.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
