# Generated by Django 2.0.7 on 2019-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/'),
        ),
    ]
