# Generated by Django 2.0.7 on 2019-05-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
