# Generated by Django 2.0.7 on 2019-05-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bookmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookManager',
        ),
    ]
