# Generated by Django 2.0.7 on 2019-05-30 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_review_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='votes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
