# Generated by Django 2.0.7 on 2019-05-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190530_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon',
            field=models.URLField(default='www.amazon.com/', max_length=400),
        ),
    ]
