# Generated by Django 2.0.7 on 2019-05-31 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20190531_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='reviews_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
