# Generated by Django 2.0.7 on 2019-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_review_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
