# Generated by Django 2.0.7 on 2019-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='votes',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
