# Generated by Django 2.0.7 on 2019-06-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190601_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/'),
        ),
    ]
